### ISSUE TITLE
Error when opening newer saves

### ISSUE THREAD

**Issue by Diniboy1123** [med1844/TheBlockheadsTools#2]
Thanks for all the incredible research. I tried this project on a newly generated map from the recently released Linux server of Blockheads and I got the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/TheBlockheadsTools/gameSave.py", line 146, in load
    return GameSave(path)
  File "/tmp/TheBlockheadsTools/gameSave.py", line 48, in __init__
    self._read_env(full_path, self._data[sub_dir])
  File "/tmp/TheBlockheadsTools/gameSave.py", line 72, in _read_env
    self._read_db(txn, sub_db, dict_[k])
  File "/tmp/TheBlockheadsTools/gameSave.py", line 82, in _read_db
    dict_[k] = self._parse(v)
  File "/tmp/TheBlockheadsTools/gameSave.py", line 105, in _parse
    result._data[0] = self._parse(result._data[0])
  File "/tmp/TheBlockheadsTools/gameSave.py", line 110, in _parse
    return self._parse(result)
  File "/tmp/TheBlockheadsTools/gameSave.py", line 121, in _parse
    src._data = self._parse(src._data)
  File "/tmp/TheBlockheadsTools/gameSave.py", line 118, in _parse
    src[k] = self._parse(v)
  File "/tmp/TheBlockheadsTools/gameSave.py", line 114, in _parse
    src[i] = self._parse(v)
  File "/tmp/TheBlockheadsTools/gameSave.py", line 118, in _parse
    src[k] = self._parse(v)
  File "/tmp/TheBlockheadsTools/gameSave.py", line 99, in _parse
    if src.startswith(b"bplist00"):  # bplist
TypeError: startswith first arg must be str or a tuple of str, not bytes
```

I assume that the protocol must have changed. If I print the string that's causing the issue, I get `OWEN`.

Found the linux server here: https://theblockheadswiki.com/wiki/Server#Linux_Server

**Comment by JarlPenguin** [comment]
Unfortunately the Linux server uses a different format, so saves created with it won't work with this tool.

**Comment by med1844** [comment]
Sorry for slow reply, I have no idea why but Github doesn't notify me this issue.

I have only tested the code for save file of version 1.7.4 from an android simulator. As JarlPenguin has mentioned, the server save file might be different from single player save files.

**Comment by Bobzilla07** [comment]
i have a save file from 1.7.4 on ios and when i try to open the file in it i get this

`from gameSave import GameSave
>>> gs = GameSave.load("./1fb91154039a981a1d994317c9d9b40f/")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/runner/TheBlockheadsTools-1/gameSave.py", line 146, in load
    return GameSave(path)
  File "/home/runner/TheBlockheadsTools-1/gameSave.py", line 48, in __init__
    self._read_env(full_path, self._data[sub_dir])
  File "/home/runner/TheBlockheadsTools-1/gameSave.py", line 67, in _read_env
    env = lmdb.open(path, readonly=True, max_dbs=self.MAX_DBS)
lmdb.InvalidError: ./1fb91154039a981a1d994317c9d9b40f/world_db: MDB_INVALID: File is not an LMDB file
>>> `

idk if its a problem with the version of the app or im just to dumb to figure out how to work this

**Comment by med1844** [comment]
I suspect it's related to 32-bit and 64-bit LMDB format, but not quite sure as I have not worked on this for 4 years.

You may try to install 32-bit and 64-bit python and install lmdb in each of them and try open the path again to see which one works.

If none of them works, then it might be iOS files having different format? I can't tell for sure.

**Comment by Bobzilla07** [comment]
if this helps here is the save file i am trying to work with
https://github.com/Bobzilla07/BLOCKHEADS-SAVEFILES

**Comment by Bobzilla07** [comment]
> Sorry for slow reply, I have no idea why but Github doesn't notify me this issue.
> 
> 
> 
> I have only tested the code for save file of version 1.7.4 from an android simulator. As JarlPenguin has mentioned, the server save file might be different from single player save files. If I have time, I will take a look into it to see if it is the case.


The 1.7.4 doesn't have any of the files mentioned in some of the script I can only find it with 2 folders world_db and map the world_db has the files data.mdb and lock.mdb

**Comment by med1844** [comment]
I finally got some time to work on this issue.

I tested the repo on the same save file that works before when I was developing this and got the same `MDB_INVALID: File is not an LMDB file` error. So, it's very likely to be 32/64-bit issue as it's not related to codebase itself.

It's hard to set up a new python environment, especially a 32-bit one, when you already have a ton of them. So, I updated the repository and added a Dockerfile so that you can use python interactive shell in docker container to load, modify, save, etc. Please refer to README for more info.

But I have to warn that even though the repo is passing all tests and seems to export without a bug in `gameSave.py:__main__`, I don't have blockhead installed on any device now, therefore I can't really tell if the exported world is correctly modified or not. I also only tested the repository on WSL Ubuntu 22.04 LTS. Though theoretically on other platforms docker should yield the same result, it might go wrong.

When I have more time, I will take a look into the linux server save file. Currently the blockheads wiki seems to be not responsive and thus I have no idea how to get that server.

**Comment by Diniboy1123** [comment]
Here: https://majicdave.com/share/blockheads_server171.tar.gz

I had to run patchelf on it to have it working on modern linux distributions.

**Comment by med1844** [comment]
I was busy recently, but according to preliminary tests the updated code that I have already commited and pushed should be able to load **copied** save folder (when I load symlinked folder it seems to crash?). The error you are encountering at first seems to be caused by incompatibility between python 2 and python 3. The repository was rewritten before to use python 2 to use 32-bit interpreter, but it turns out that python 2 is not the only way to load a 32-bit save file. Now the codebase has migrated back to python 3!

I can't tell if the modified world data would be loadable by the server. The test world also has no user data as I still have no blockhead installed on any device.

I plan to look into it when I got more time, most probably after spring semester. Thanks for providing server, this should greatly help development as I don't have to drag & replace files in simulators manually, and the save files are stored in 64-bit meaning the development won't be stumbled by docker containers!

**Comment by Xeunon** [comment]
Hello, kudos on the project 👏.
I have been playing around with a one of my own server saves. 
I am able to load the file. I am also able to get and set blocks; but I have been unable to get to any of the blockheads' inventories. (Obviously haven't been able to change any items in those inventories either).
The main difference that I have found is that in the single player file, the inventory data structure is a bplist whereas the server inventory file is a gzipwrapper type. 
Any tips on how I can extract the data from the gzipwrapper? or are you working on it yourself?

**Comment by med1844** [comment]
> Any tips on how I can extract the data from the gzipwrapper? or are you working on it yourself?

`gzipWrapper._data[0]` should give you the internal data.

I'm not working on this project, as I currently have no device that allows me to run the game.

Please feel free to create a fork to fix things that's not working on your save file!

**Comment by Xeunon** [comment]
> `gzipWrapper._data[0]` should give you the internal data.

That worked right away! I have access to inventories too.
There's the small issue of saving the edited files.  I run into this error:
`lmdb.MapFullError: mdb_put: MDB_MAP_FULL: Environment mapsize limit reached`
My game's map size is 1x.  Any tips on this problem? Thanks in advance.

**Comment by med1844** [comment]
> `lmdb.MapFullError: mdb_put: MDB_MAP_FULL: Environment mapsize limit reached`

I'm not very sure about this but I think it's lmdb's issue, and have nothing to do with the game map size.

Instead I suspect it's related to these lines:

https://github.com/med1844/TheBlockheadsTools/blob/610de50da1a0c3fa1a6f55df914270e4d6c16efd/gameSave.py#L155-L172

Specifically,

```python
     env = lmdb.open(path, map_size=size << 3, max_dbs=self.MAX_DBS)
```

Try tweak the map_size. Currently I'm using 8x of the sum of length of all entries... you can try 16x by doing `size << 4` or even 32x with `size << 5`. I'm not very certain about the role of map size here. When I was developing this I just randomly 8x-ed that number, so that I can add new features first before figuring out the right way to set map_size and deal with storage settings. You can also take a deeper look into the [python lmdb doc](https://lmdb.readthedocs.io/en/release/).
